import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/Navbar/Navbar";
import Footer from "@/components/common/Footer/Footer";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="min-h-screen flex flex-col bg-gradient-to-br from-blue-50 to-transparent">
          {/* <div className="absolute top-32 right-0 w-[50%] h-[600px]">
            <Image
              src="/investors-1.svg"
              alt="AI Brain Illustration"
              fill
              className="object-contain object-right"
              priority
            />
          </div> */}
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
